### Sending reqeust with rest client extenstion with vscode

### Otp sending route
POST http://localhost:4000/api/login 
Content-Type: application/json

{
    "email": "jacksparrow.mdjack@gmail.com"
}

### Otp verification route
POST http://localhost:4000/api/verify
Content-Type: application/json

{
    "email": "jacksparrow.mdjack@gmail.com",
    "otp": "2342"
}

### Form apply route
POST http://localhost:4000/api/apply-cl 
Authorization: Bearer 
Content-Type: application/json

{
    "arrangements": [
        {
            "date_hour": "01-12-2000 12:00 PM", 
            "class": "CSE A",
            "subject": "AI",
            "year": "2"
        }
    ],
    "basic": {
        "name": "Jack",
        "designation": "Tutor",
        "nature_of_leave": 1,
        "availed_days": "3",
        "period_from": "01-12-2000",
        "period_to": "05-12-2000",
        "no_of_days": 4,
        "phone_number": "9524369244",
        "country_code": "91",
        "department_name": "cse",
        "semester_type": "odd",
        "purpose_description": "sample description"
    },
    "address": {
        "line1": "1/2, street, nehury",
        "line2": "Neary hospital",
        "city": "Trichirappalli",
        "state": "Tamilnadu",
        "postal_code": "621216",
        "country": "India"
    }
} 