### Sending request with rest client extension with vscode

### Otp sending route
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "jacksparrow.mdjack@gmail.com"
}

### Otp verification route
POST http://localhost:4000/api/verify
Content-Type: application/json

{
    "email": "jacksparrow.mdjack@gmail.com",
    "code": "148805"
}

### Form apply route
POST http://localhost:4000/api/apply-cl
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzYW50aG9zaHZlbHJAZ21haWwuY29tIiwiaWF0IjoxNjM0NjM4OTM3LCJleHAiOjE2MzcyMzA5Mzd9.ajV0g8_le9aX_3a-Up4p1J0qo61M0hHx0OwBbEfPLYE
Content-Type: application/json

{
    "arrangements": [
        {
            "date_hour": "01-12-2000 12:00 PM",
            "class": "CSE A",
            "subject": "AI",
            "year": "2"
        }
    ],
    "basic": {
        "name": "Jack",
        "designation": "Tutor",
        "nature_of_leave": 1,
        "availed_days": "3",
        "no_of_days": 2,
        "phone_number": "9524369244",
        "country_code": "91",
        "department_name": "cse",
        "semester_type": "odd",
        "purpose_description": "sample description"
    },
    "address": {
        "line1": "1/2, street, nehury",
        "line2": "Neary hospital",
        "city": "Trichirappalli",
        "state": "Tamilnadu",
        "postal_code": "621216",
        "country": "India"
    },
    "dates": ["01-12-2000","02-12-2000"]
}

### Auth verification route
GET http://localhost:4000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzYW50aG9zaHZlbHJAZ21haWwuY29tIiwiaWF0IjoxNjM0NDUyNjE3LCJleHAiOjE2MzcwNDQ2MTd9.Vwc7NEPYXulAnxn_LchAAhpHzHzgPdypZ96G4Sj9wFo
Content-Type: application/json
