-- MySQL Script generated by MySQL Workbench
-- Tue Oct 19 15:36:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cl_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cl_database` ;

-- -----------------------------------------------------
-- Schema cl_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cl_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cl_database` ;

-- -----------------------------------------------------
-- Table `cl_database`.`arrangements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl_database`.`arrangements` ;

CREATE TABLE IF NOT EXISTS `cl_database`.`arrangements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cl_id` INT NULL DEFAULT NULL,
  `date_hour` DATETIME NULL DEFAULT NULL,
  `class` VARCHAR(256) NULL DEFAULT NULL,
  `subject` VARCHAR(256) NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `cl_id` (`cl_id` ASC) VISIBLE,
  CONSTRAINT `arrangments_ibfk_1`
    FOREIGN KEY (`cl_id`)
    REFERENCES `cl_database`.`cl_informations` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cl_database`.`cl_informations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl_database`.`cl_informations` ;

CREATE TABLE IF NOT EXISTS `cl_database`.`cl_informations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `staff_id` INT NULL DEFAULT NULL,
  `staff_address_id` INT NULL DEFAULT NULL,
  `uis` VARCHAR(64) NULL DEFAULT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `designation` VARCHAR(128) NULL DEFAULT NULL,
  `nature_of_leave` TINYINT NULL DEFAULT '0',
  `availed_days` TINYINT NULL DEFAULT '1',
  `no_of_days` INT NULL DEFAULT '1',
  `phone_number` VARCHAR(64) NULL DEFAULT NULL,
  `country_code` VARCHAR(4) NULL DEFAULT '91',
  `department_name` VARCHAR(64) NULL DEFAULT NULL,
  `semester_type` VARCHAR(16) NULL DEFAULT NULL,
  `purpose_description` VARCHAR(256) NULL DEFAULT NULL,
  `is_recomended` TINYINT NULL DEFAULT '0',
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `staff_id` (`staff_id` ASC) VISIBLE,
  INDEX `staff_address_id` (`staff_address_id` ASC) VISIBLE,
  CONSTRAINT `cl_informations_ibfk_1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `cl_database`.`staffs` (`id`),
  CONSTRAINT `cl_informations_ibfk_2`
    FOREIGN KEY (`staff_address_id`)
    REFERENCES `cl_database`.`staff_addresses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cl_database`.`dates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl_database`.`dates` ;

CREATE TABLE IF NOT EXISTS `cl_database`.`dates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `cl_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dates_cl_informations1_idx` (`cl_id` ASC) VISIBLE,
  CONSTRAINT `fk_dates_cl_informations1`
    FOREIGN KEY (`cl_id`)
    REFERENCES `cl_database`.`cl_informations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl_database`.`staff_addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl_database`.`staff_addresses` ;

CREATE TABLE IF NOT EXISTS `cl_database`.`staff_addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `staff_id` INT NULL DEFAULT NULL,
  `line1` VARCHAR(256) NULL DEFAULT NULL,
  `line2` VARCHAR(256) NULL DEFAULT NULL,
  `city` VARCHAR(64) NULL DEFAULT NULL,
  `state` VARCHAR(64) NULL DEFAULT NULL,
  `postal_code` VARCHAR(64) NULL DEFAULT NULL,
  `country` VARCHAR(64) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `staff_id` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `staff_addresses_ibfk_1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `cl_database`.`staffs` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cl_database`.`staffs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl_database`.`staffs` ;

CREATE TABLE IF NOT EXISTS `cl_database`.`staffs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `code` VARCHAR(16) NULL DEFAULT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `department` VARCHAR(128) NULL DEFAULT NULL,
  `staff_id_number` INT NULL DEFAULT NULL,
  `is_verified` TINYINT NULL DEFAULT '0',
  `is_active` TINYINT NULL DEFAULT '1',
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
